import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/utils/logger.dart';
import 'firebase_options.dart';

/// Top-level background message handler. Runs in its own isolate when the
/// app is fully killed and a push arrives — so it MUST be a top-level
/// function and MUST initialize Firebase on its own.
///
/// We don't render anything here; the Cloud Function already wrote the
/// in-app notification row, so when the user opens the app they'll see
/// it in the bell. This handler just exists so Android shows the system
/// banner reliably.
@pragma('vm:entry-point')
Future<void> _onBackgroundMessage(RemoteMessage message) async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (_) {
    // Already initialized — fine.
  }
}

 Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait — change here if landscape support is needed.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Catch any uncaught framework errors and route to our logger.
  FlutterError.onError = (details) {
    appLogger.e(
      'FlutterError: ${details.exceptionAsString()}',
      error: details.exception,
      stackTrace: details.stack,
    );
  };

  // Initialize Firebase. `firebase_options.dart` is generated by
  // `flutterfire configure` — see FIREBASE_ARCHITECTURE.md.
  //
  // If init fails (bad config, no network at cold start), do NOT boot the
  // normal app — every Auth/Firestore call would throw and the user would
  // see a cascade of raw errors. Show a dedicated failure screen instead.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e, st) {
    appLogger.e('Firebase init failed', error: e, stackTrace: st);
    runApp(const _FirebaseInitErrorApp());
    return;
  }

  // Firebase App Check — anti-abuse for Firestore / Storage / Functions.
  // Debug provider on debug builds (register the token printed in logcat
  // in Firebase Console → App Check); Play Integrity on release. Stays
  // NON-enforced until enforcement is toggled on in the console.
  try {
    await FirebaseAppCheck.instance.activate(
      androidProvider:
          kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
      appleProvider:
          kDebugMode ? AppleProvider.debug : AppleProvider.appAttest,
    );
  } catch (e, st) {
    appLogger.w('App Check activate failed', error: e, stackTrace: st);
  }

  // Register the FCM background handler BEFORE the app starts so a push
  // arriving in the kill-state isolate can wake the handler up.
  FirebaseMessaging.onBackgroundMessage(_onBackgroundMessage);

  runApp(const ProviderScope(child: App()));
}

/// Minimal standalone app shown when Firebase fails to initialize. Kept
/// dependency-free (no providers/router) so it can render even when the
/// rest of the app's wiring is unavailable.
class _FirebaseInitErrorApp extends StatelessWidget {
  const _FirebaseInitErrorApp();

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Color(0xFFF4F1FA),
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(32),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.cloud_off_rounded, size: 56),
                SizedBox(height: 20),
                Text(
                  "Couldn't connect",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w700,
                    color: Color(0xFF1A1A22),
                  ),
                ),
                SizedBox(height: 10),
                Text(
                  'Reset95 could not reach its servers. Check your internet '
                  'connection and reopen the app.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 15,
                    height: 1.5,
                    color: Color(0xFF6E6E7C),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
