import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/utils/logger.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait — change here if landscape support is needed.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Catch any uncaught framework errors and route to our logger.
  FlutterError.onError = (details) {
    appLogger.e(
      'FlutterError: ${details.exceptionAsString()}',
      error: details.exception,
      stackTrace: details.stack,
    );
  };

  // Initialize Firebase. `firebase_options.dart` is generated by
  // `flutterfire configure` — see FIREBASE_ARCHITECTURE.md.
  //
  // If init fails (bad config, no network at cold start), do NOT boot the
  // normal app — every Auth/Firestore call would throw and the user would
  // see a cascade of raw errors. Show a dedicated failure screen instead.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e, st) {
    appLogger.e('Firebase init failed', error: e, stackTrace: st);
    runApp(const _FirebaseInitErrorApp());
    return;
  }

  runApp(const ProviderScope(child: App()));
}

/// Minimal standalone app shown when Firebase fails to initialize. Kept
/// dependency-free (no providers/router) so it can render even when the
/// rest of the app's wiring is unavailable.
class _FirebaseInitErrorApp extends StatelessWidget {
  const _FirebaseInitErrorApp();

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Color(0xFFF4F1FA),
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(32),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.cloud_off_rounded, size: 56),
                SizedBox(height: 20),
                Text(
                  "Couldn't connect",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w700,
                    color: Color(0xFF1A1A22),
                  ),
                ),
                SizedBox(height: 10),
                Text(
                  'NammaSign could not reach its servers. Check your internet '
                  'connection and reopen the app.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 15,
                    height: 1.5,
                    color: Color(0xFF6E6E7C),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
